### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by Hywan** [khaledhosny/euler-otf#16]
Hello :-),

What is the state of this project please? Is it in pause, dead, inactive?

**Comment by ArchangeGabriel** [comment]
But there hasn’t been news since… Any update? This is a very great font, and my new default together with EB Garamond in my documents. :)

**Comment by khaledhosny** [comment]
This project is dead for all practical purposes, I tried twice to revive it but I couldn’t get myself to work on it both times and I just abandoned it last year. May be I should update the REAME to make this clear.

**Comment by ArchangeGabriel** [comment]
Oh, that’s sad… But I understand your lack of motivation to get back on work on an old unfinished project. I have myself quite a bunch of stalled projects for which I mostly need time, but I finally often lack of motivation when I manage to get some free time.

I honestly don’t know how much it takes to do so, but could you at least consider merging blackboard part into master if that’s not too demanding?

But most importantly, keep up doing great things around free and open fonts!

**Comment by Hywan** [comment]
:-( Too bad. But thank you for the hard work!

**Comment by ArchangeGabriel** [comment]
The number of Unicode Math fonts grows slowly, but I still can’t find one that suits EB Garamond as Euler does… Good thing is Euler almost works for my use cases, the most outstanding issue being wrong spacing in subscripts.
